//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_QLBH_BQD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Project_Equipment = new HashSet<Project_Equipment>();
            this.Categories = new HashSet<Category>();
        }
    
        public int equipment_id { get; set; }
        public string equipment_code { get; set; }
        public string equipment_name { get; set; }
        public string serial_no { get; set; }
        public Nullable<System.DateTime> import_date { get; set; }
        public string unit { get; set; }
        public string specification { get; set; }
        public string img { get; set; }
        public string location { get; set; }
        public string responsible_person { get; set; }
        public string status { get; set; }
        public string note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Equipment> Project_Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
    }
}
