//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_QLBH_BQD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Request_Application_Detail
    {
        public int application_detail_id { get; set; }
        public string application_code { get; set; }
        public string equipment_code { get; set; }
        public string stock_number { get; set; }
        public string equipment_status { get; set; }
        public string notes { get; set; }
    }
}
