//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELMs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Member
    {
        public int project_id { get; set; }
        public int user_id { get; set; }
        public string position_code { get; set; }
        public string notes { get; set; }
        public string status { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
