//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELMs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Equipment
    {
        public int project_id { get; set; }
        public int equipment_id { get; set; }
        public Nullable<System.DateTime> borrow_date { get; set; }
        public int application_id { get; set; }
        public string borrower { get; set; }
        public string equipment_status { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Project Project { get; set; }
    }
}
