//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELMs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Investment_Cost_Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project_Investment_Cost_Application()
        {
            this.Project_Investment_Cost_Application_Detail = new HashSet<Project_Investment_Cost_Application_Detail>();
        }
    
        public int application_id { get; set; }
        public Nullable<System.DateTime> application_date { get; set; }
        public int project_id { get; set; }
        public string title { get; set; }
        public string reason { get; set; }
        public string notes { get; set; }
        public string created_by { get; set; }
        public Nullable<decimal> total_cost { get; set; }
        public string attachment_path { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> approve_date { get; set; }
        public string approver { get; set; }
        public string approver_notes { get; set; }
    
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Investment_Cost_Application_Detail> Project_Investment_Cost_Application_Detail { get; set; }
    }
}
